### ISSUE TITLE
On login page the wallets sometimes vanish from the dropdown menu

### ISSUE THREAD

**Issue by NanukHe** [NemProject/NanoWallet#11]
This happened for my stepfather's wallet and, I also just before that, tried my nano with Mozilla Firefox, with the same issue, but in my Safari it works just fine. My stepfather uses Safari with the history deletion on and maybe some other security settings also in browser, but it completely forgot his wallet. So I showed him how to have a new wallet, and finally when he found his private keys :). He also, after that, found this: https://forum.nem.io/t/nano-wallet-help/3157/4?u=generaattori
Where the same issue is addressed with photos attached. I don't know nano architecture but for me it would be nice if it worked in all the browsers of one computer. Even my stepfather who is not an it-man said that: shouldn't the memory be in the files of nano, not in browser. What this can be, I can only speculate, but maybe it has something to do with security settings or even (this is quite far away) updates of browser?? Still I found this, that big issue, that if I would be in hurry, I would maybe use ncc, because it doesn't forget the wallets and it seems now firm. it takes time to retrieve the wallet with the private key :)
![nem-loginscreen](https://cloud.githubusercontent.com/assets/22426244/23091414/051ceaac-f5be-11e6-8e39-b49eb28262c1.png)

**Comment by Kuppi74** [comment]
I had same issue lately, with windows10/chrome.

**Comment by QuantumMechanics** [comment]
Hi,

Nano use browser local storage to store your wallets and other data, so depending of your browser settings it'll keep data for a long time or clean it if closed.

For security reasons JavaScript is not allowed to access / edit your files directly. So unlike NCC we can't find wallets stored in a dedicated folder and load it automatically.

It is not a problem, if you have your .wlt file you just have to import it again via login page.

>  it takes time to retrieve the wallet with the private key :)

I don't understand why you guys all insist on retrieving the wallet with the private key when you have a .wlt file given to you each time you create a new wallet ^^ 

If you don't have it either you rejected the download or the app has a problem, because it must always trigger the download on every browser.

**Comment by Kuppi74** [comment]
ok, thx for answer. 
I used .wlt back then succesfully.
