### ISSUE TITLE
Sent NEM with message encrypted to Poliniex

### ISSUE THREAD

**Issue by edrod1704** [NemProject/NanoWallet#170]
I sent some NEM to Poliniex with the message encrypted. I believe they can not read the message with the info they need to credit my account with them. Is there anything you can do to help me from your side?. I have already posted two tickets with Poliniex but they have not answered any of them.

**Comment by mizunashi** [comment]
Poloniex support is very crowded.
Please wait for a while or inform me of the new ticket collection situation.
In order to report the situation, please tell the following contents
· Encrypted messege
· Transaction number

*READ*
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
