### ISSUE TITLE
Wallet bug

### ISSUE THREAD

**Issue by timkug** [NemProject/NanoWallet#233]
The Start/Stop Harvesting button on the bottom right is greyed out. I can pick a new node with open slots, but can't use that button anymore.  My status is Active.  I can choose a new node, but can't start it.  If I leave and come back, it reverts to the old node with no slots.

This problem started over a month ago.  I have tried the forums already.

Thanks,
Tim

**Comment by QuantumMechanics** [comment]
Hi,

I will look into it asap

**Comment by timkug** [comment]
I just installed the latest wallet (1.4.3 from 1.3) and it did not help, so I sent 6 XEM to deactivate harvesting.  Looks like I will have to wait until tomorrow while it is processing before I can send another 6 XEM to activate.  I'll see it that fixes it.  Kind of like a reboot.

**Comment by timkug** [comment]
Well, that didn't work.  Remote Status is Active, Harvesting Status is Inactive.  The big Start Delegated Harvesting button is greyed out on all open slots.

**Comment by mizunashi** [comment]
Would you please send us a screenshot of the part below "Start / Stop delegated harvesting"?

**Comment by timkug** [comment]
Do you have a link where the people at NEM say that it is safe to give that out?
Here is an image without that info for now.
![untitled-2](https://user-images.githubusercontent.com/28925026/28848463-fe2191ea-76e0-11e7-82b0-276de23fe8fc.jpg)

Thanks,
Tim

**Comment by mizunashi** [comment]
Please enter your password on the red line on the bottom right side.
By entering the password, you can select the harvesting node and start (and stop) the operation.

After entering the password, press the "Start delegated harvesting" button at the bottom to start harvesting.
At this time, if the message "No free slots on selected node, please please another" continues to be displayed under the button, please choose a different node.

Harvesting stops when Supernode restarts.
Currently, since it is in the period of version upgrade of Supernode, I think that it is better to check if harvesting is continuing continuously than usual.

thanks

**Comment by timkug** [comment]
That worked, I am back in business.
Thanks,
Tim
