### ISSUE TITLE
Not working replenishment XEM

### ISSUE THREAD

**Issue by Danilwork** [NemProject/NanoWallet#336]
Not working replenishment XEM wallet Yobit and Hitbit. In Nanowalett sending Yobit does not pass - is already half the state of sending the transaction. - 

"Please note that XEM deposits are temporarily unavailable due to technical maintenance. Please accept our apologies for the inconvenience."

 Previously, everything was normal version 1.4.13. What happened to XEM NEM?

**Comment by pawelmi** [comment]
It looks like issue with exchange wallet. In what why it's related with nano? Have you more Informations about this issue from exchange? If it's problem with nano could you attach print screen?

**Comment by QuantumMechanics** [comment]
Hi,

Not a NanoWallet issue, just a problem on their side.

**Comment by Danilwork** [comment]
Hi. Thank you for your prompt response.
 But the technical work is proceeding on two different exchanges. So what is happening in the network NEM. And I have the transaction hanging for the third day, if the problem is on the other side, then the sending should be cancelled or leave and there is not be credited. I have a positive balance does not increase and the coins hang, I can't even cancel it.
![image](https://user-images.githubusercontent.com/32951184/33754532-aa493884-dbfd-11e7-8d5f-3a8bd51b5947.png)

**Comment by cryptoBeliever** [comment]
Nothing is happening in NEM network. No updates, no technical problem.
Transactions will be noy canceled because in NEM network they are processed correctly. Problem is only that exchange doesn't present you correct informations because they have technical problems in my opinion. 
You should contact with exchange and ask what happen. 
I'm asking too via Facebook but not clear answer from yobit and hitbtc. 
No matter what this is not problem with NEM or  wallet. 
If you want continue this discussion please do on official forum
https://forum.nem.io/t/xem-wallet-maintenance-on-yobit/9657/6. 

I suggest to contact with exchange support. If they receive more signals maybe they fix this quicker.
