### ISSUE TITLE
No error is showed when cosign is added without public key

### ISSUE THREAD

**Issue by Sateetje** [NemProject/NanoWallet#356]
## Expected Behavior
Showing a message when a cosign account is added to multisig account when cosign account doesn't have a public key, because he didn't do a transfer yet

## Current Behavior
No error message is showed

## Possible Solution
See old nano wallet. The old showed this message: Cosignatory must have at least one transaction to get a public key!

## Steps to Reproduce
1. Make new account
2. Add this account to multisig account
3. Buttons stays disabled, but you cannot see why (old version showed the error)

## Details
My new account was a trezor account

OS: W7 with Firefox dev and Nano 2.0.2

NBXNJ2-FH2K52-ZOOI3A-2ZY4AW-YQJ7LV-AITSZX-KZWI

**Comment by QuantumMechanics** [comment]
Hi,

I forgot to let the button enabled. Now user is notified about the missing public key after clicking on the `add` button.

Now fixed in 2.0 https://github.com/NemProject/NanoWallet/commit/6555d1f746114c8c06eddefb77d4687d9b96c8f5 https://github.com/NemProject/NanoWallet/commit/808f243d73c577a93cf93a959ccf93120e80ebb7

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 5b939da1eb1ebbc66697b7633dfe0f5922c4ce892f95457640c707c1d340b4ae
