### ISSUE TITLE
Empty Transaction

### ISSUE THREAD

**Issue by nick7380** [NemProject/NanoWallet#38]
I tried to send 11,000 Nem to Desktop address from mobile wallet address and all 11,000 went to fees. How do I get my 11,000 back? and why did it all go to fees? and not back to wallet?

Transfer transaction
From NC5DQV-NGV6SG-LOYACB-NI7AXT-A76W6L-7I5LYP-NRUF
To NDE6IF-CMJIZM-APD5R6-2FLQY7-GV3DQT-K5M3BF-D3CW
Amount0.000000 XEM
Fee 11 000.000000 XEM
Block 1039636
Hash 85a45c5a4d8af1b925852156d87591d359b4e96c803192f9c090f6b2160dadfd

**Comment by saulgray** [comment]
This issue has nothing to do with Nanowallet. Nanowallet does not allow users to pay more than the required fee in a transaction. 

I agree android app should not allow you to send such a high fee, you can report the issue here if you like: https://github.com/NemProject/NEMAndroidApp

Please keep in mind, your XEM is gone. It has been given to the harvester who found the block your transaction was in.

**Comment by nick7380** [comment]
Lucky harvester!!!
