### ISSUE TITLE
Transactions have dissappeared

### ISSUE THREAD

**Issue by siphon11** [NemProject/NanoWallet#404]
Windows 10 / Opera

## Expected Behavior
Sent 2 transactions from my NEM desktop wallet to Bittrex.
Expected to be received in my Bittrex account.

## Current Behavior
They have not been received by Bittrex 4 hours later.
The hashs given for each transaction are not recognised in ETHERSCAN

**Comment by siphon11** [comment]
Details of one of the transaction below:
Amount 1 500.000000 XEM
Fee 0.200000 XEM
Message Encrypted --> Decode 
Block 1445736
Hash 4c63eb4cae2c3a948e0fbe332d4262c7e55b5363fd3b592c27717e8c386adddf

**Comment by QuantumMechanics** [comment]
Hi,

You sent an encrypted message. Transaction reached Bittrex but they are not able to know it is you because they don't decrypt messages.

http://chain.nem.ninja/#/transfer/4c63eb4cae2c3a948e0fbe332d4262c7e55b5363fd3b592c27717e8c386adddf 

Contact them and tell them you sent an encrypted message.
