### ISSUE TITLE
[2.0 only]About transmission of mosaic

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#432]
Before submitting your issue, please review the following checklist:

- [✓ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [✓ ] **DO** describe operating system and browser used

## Details
When transmitting a mosaic at NanoWallet 2.0.14, it will be "INSAFIENT_FEE" under certain conditions and can not be transmitted.

As long as you have tested multiple times, the following conditions are effective.

When sending: When sending one or two mosaics.
In case of error: When sending three or more mosaics.

Please confirm.

![2018-01-19 8 11 56](https://user-images.githubusercontent.com/1645189/35127022-74a5c640-fcf3-11e7-94b7-94663d7ed80d.png)

**Comment by petrofang** [comment]
I have done some experimenting and found that I am only able to transfer up to 2.444 units of a mosaic (divisibility factor of 3) in Nanowallet 2.0.14 Windows 10. 
As mizunashi mentioned, the error was INSUFFICIENT_FEE when sending 2.445 or more g:units on the testnet.  The bug is, perhaps, introduced when clicking "Mosaic transfer" by erroneously reducing the transfer fee by 0.05 XEM, or in some other way miscalculating transfer fees.  
I hope this helps a little.
(edit for detail and clarity)

**Comment by QuantumMechanics** [comment]
Hi,

Should be fixed in https://github.com/QuantumMechanics/NEM-sdk/commit/f58553785a563407750d4fabd51b5fe888c6f4c4
