### ISSUE TITLE
Put the Windows Version in the Windows Store

### ISSUE THREAD

**Issue by MelbourneDeveloper** [NemProject/NanoWallet#449]
## Expected Behavior
I can download the app from the Windows Store.

## Current Behavior
I can't download the app from the Windows Store.

## Possible Solution
Put the app in the the Windows Store.

## Steps to Reproduce
1. Go to the Windows Store
2. Notice you cannot download the app

## Details
Your user base is very security savvy. A lot of people will not download the app because it is not in the store and will be worried that it's full of malware.

Also, the app should be written in UWP. The UI is non-standard for Windows 10.

**Comment by QuantumMechanics** [comment]
Hi,

I don't think it will ever be on the Windows store. I have never been okay with the Chrome packaged apps for Linux, OSX and Windows. 

I want them to be dropped because we have no control on the third party module used to bundle everything (https://www.npmjs.com/package/nw), bundling introduce minor bugs that we cannot fix directly, it has no support for Trezor and the apps are so big it takes 2 hours for packaging everything and publishing the versions...

My vision was only the universal client, light and fully in JavaScript, that you can simply start once from any machine with a `start.html` file and put a bookmark on the page to start the wallet directly from your browser.
