### ISSUE TITLE
NEM with Trezor One Harvesting does not work

### ISSUE THREAD

**Issue by Hellracer88** [NemProject/NanoWallet#501]
Hello, I now have my NEM on the Trezor Wallet. Use the universal wallet from the NEM side that is for Trezor.

I've activated harvesting.

It's also active. 
Problem is that when I log out of the trezor wallet the harvesting is disabled 1 day after that.

Currently, harvesting with the Trezor Universal Wallet does not work. When logging off, harvesting is disabled.

**Comment by cryptoBeliever** [comment]
Please verify if your selected node on harvesting page doesn't change after login next day using Trezor.
Because nanowallet checks in current selected node you must change again to this one where you started harvesting. 

You can also activate harvesting using nem-tools: https://www.youtube.com/watch?v=_m7rvXiEFpo
