### ISSUE TITLE
Unable to send more than 1000 mosaic

### ISSUE THREAD

**Issue by setonfire89** [NemProject/NanoWallet#527]
Hi,

Ran into a bug on current nanowallet v2.2.0 from https://nem.io/downloads/

After setting up multisig and cosign account, facing issue transferring more than 1000 mosaic from cosign account.

Error message: FAILURE_INSUFFICIENT_FEE

Tested on both mainnet and testnet, same issue.

A screenshot of error message.

![image](https://user-images.githubusercontent.com/29622342/41248643-418b02ae-6de4-11e8-995d-180a724f9cf8.png)

Verify with admin from https://t.me/nemhelpdesk that this is due to fee issue on the nanawallet v2.2.0. Manually increasing the fee allows higher limit of transfer.

![image](https://user-images.githubusercontent.com/29622342/41248779-97ad3800-6de4-11e8-8e63-9dc272b8a020.png)

Believe its a bug on the new nanowallet version where the max fee set is not executing.

Kindly assist.

Thank you

On a sidenote, was told i will receive a bounty on this.

![image](https://user-images.githubusercontent.com/29622342/41248832-c057aeac-6de4-11e8-8280-b5d4e3bc3bb7.png)

Bounty: NDW4YEGW4RCSGCCECPMDNEX2UTHXMFQANQHCNTIW

**Comment by mizunashi** [comment]
This is not because it is a 1000 mosaic.
Depending on the number of mosaics issued and the mosaic to be sent, the transaction Fee changes.
This is to calculate the number of issued and transmission fee converted into XEM issue number and transmission fee.

Transfer Transaction is a single remittance of NEM or Mosaic, up to 1.25 x em. If there are many assets to be remitted, Fee will be generated for each asset.
With the exception, for small bisiness mosaic only, it is fixed at 0.05 x em.
In addition, it will cost Fee up to 1.65 x em with only message.

So far, it is displayed as a total value on the left side of the Fee column.


In addition, in the case of multi-sig account, Fee is displayed behind +.

Actually, though it is thought that you can remit money with these total values, multi-sig Fee also depends on how to configure multi-sig.

In my memory, it has been confirmed that accurate values ​​can not be displayed from the beginning of NanoWallet, and it also exists in issue on github.
Therefore, it is a known problem.

Thank you.

@QuantumMechanics 
Correct it if I am wrong.

**Comment by cryptoBeliever** [comment]
There is bug in nanowallet fee calculation for mosaics. I will post pull request soon. Consultated with BloodyRookie.

**Comment by cryptoBeliever** [comment]
@QuantumMechanics please look at pull request. Thank you.

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/QuantumMechanics/NEM-sdk/pull/49

**Comment by fyahfox** [comment]
bounty paid
TX hash: 6e9b01b2099fea672d5fe5fce042f6f3ac964078c15c7ed88648c855cb53ea40
