### ISSUE TITLE
Empty Dashboard with Node Connected Successfully

### ISSUE THREAD

**Issue by johnchin12345** [NemProject/NanoWallet#599]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Expected Behavior
Dashboard should display all posted and unposted transactions and have notification when a transaction is coming in

## Current Behavior
Dashboard is totally empty and no notification

## Steps to Reproduce
1. Log in
2. View dashboard

**Comment by cryptoBeliever** [comment]
I'm not able to reproduce using the following steps on the latest version. If you have more information please attach it to the issue.
If problem still exists (it's unlikely since 2 years passed) please try also switching the node and make sure that your VPN/Network Provider is not blocking the connection to a node on ports 7890 and 7778.
