### ISSUE TITLE
address display 

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#82]
When the screen of the PC is small, the address is not displayed completely.
![address](https://cloud.githubusercontent.com/assets/22280874/25768863/a3bfe9aa-3247-11e7-9e29-637a7b7bddc1.png)
![s__1196035](https://cloud.githubusercontent.com/assets/22280874/25768864/a6f8b818-3247-11e7-8549-fde2cebc4511.jpg)
Solving the problem by extending the screen, but it is impossible to fully display by default on my personal computers.

**Comment by mizunashi** [comment]
@RightBlume  What you are looking for is a solution like the following?

![address](https://cloud.githubusercontent.com/assets/1645189/25769382/08bfa916-3253-11e7-94b7-7ed2fe09a230.gif)

**Comment by RightBlume** [comment]
Yes！
Solve quickly desu.

**Comment by mizunashi** [comment]
For confirmation, I rewrote the source file and made it.
However, in this method, since we rewrite the style sheet style sheet, it will be affected elsewhere.

The changes are as follows.
File: ///......./src/sass/_new.scss

  300:  fieldset. Form-control {
  301:  // overflow: hidden; // to comment
  302:  overflow: scroll; // change scroll
  303:  white-space: nowrap;
  304:  // text-overflow: ellipsis; // to comment
  305:  max-width: 260 px;
  306: }

If there is demand for this & paste, I think that it corresponds to scrolling only the address of NEM.
Regarding the public key, there are not too many scenes to use, so I think that it is good as it is before.

This is a test, so I will not fix the actual source code.
Let the development side judge.

**Comment by cryptoBeliever** [comment]
There was added copy button so I think it's fine now.
