### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by cryptocali** [NemProject/NanoWallet#83]
Hi All,

I'm new to NEM and just downloaded the wallet last night.  When I click on the Account tab it looks all funky.  I tried reinstalling and searching for similar issues online.  Any and all help would be greatly appreciated!

![screen shot 2017-05-06 at 6 44 21 pm](https://cloud.githubusercontent.com/assets/28495669/25777270/4749f666-328d-11e7-98da-ee7b8f3dd3c5.png)

**Comment by mizunashi** [comment]
Did you download the source code from GitHub and downloaded it from the official site rather than build it?
Other than developers, download from the official site.

On the official website, [NanoWallet 1.3.4 (20th / Apr) version](https://www.dropbox.com/s/easnn1uzct8dras/NanoWallet-1.3.4%20--%20Apostille%20TX%20f9a506e3abfa225d60b4447017279a6af7561428e0f53839fb3bea92fe8c129d%20--%20Date%202017-04-20.zip?dl=0) is distributed.

Do you reproduce the phenomenon even if you use a different browser?
If it does not work with a different browser, please send the following contents.

Please tell me the following information.
・OS（Windows,MacOS,Linux etc & Version number）
・Your browser and its version number

**Comment by cryptocali** [comment]
Hi Rin, thanks for the feedback!  I downloaded the NanoWallet from the official website, and was using Safari.  I was able to download Google Chrome and create a new Simple Wallet, and the issue I described was not there.  I also updated my OS to the latest version (OS X Yosemite Version 10.10.5).  Although the issue still exists on Safari (Version 8.0.8).

I can use Google Chrome from now on, but is there a way to upload the wallets I created in Safari to the Google Chrome browser?

Sorry for all the questions.  I'm new to the crypto-world and was able to figure out Ethereum Mist and transferring tokens, but I'm a little stuck when it comes to NEM NanoWallet.

Thanks!

**Comment by mizunashi** [comment]
If you are using MacOS, we recommend Google Chrome. Safari has confirmed the strange part of behavior is current.

Describe the method for maximally safe migration.

![2017-05-07 12 40 38](https://cloud.githubusercontent.com/assets/1645189/25777814/9bbbdccc-3324-11e7-904e-21d5e8f2ce69.png)

If you have created more than one account, please change here and repeatedly note 1 & 2.

In the part 3, all wallets (NanoWallets can have multiple wallet files) are displayed without switching Account.
Just to be sure, please back up all displayed wallet files.
In one wallet file, one .wlt file is created.

If you only have a .wlt file in fact, importing it into a new wallet will restore all the information.
If you can not do it, you can load the private key and restore it. However, in this case we recommend that you use the old one for your Wallet name and Wallet password in order to avoid various problems later.

Thanks

**Comment by mizunashi** [comment]
@cryptocali 
Has the problem been resolved?

**Comment by cryptocali** [comment]
Hi Rin,

Yes, I was able to backup all of my wallets and everything is working great.  Thank you so much for the help!
